### PR TITLE
Fixed "Property style on undefined"

### PR DESCRIPTION
**Pull request by ankit22687**
Found issue before set icon style, so I just wrap those with If condition and it is working fine now.

### CODE REVIEW

**Comment by hosuaby** [comment]
Only style of the code was changed. Indentation, etc. But no fix in sight

**Comment by ankit22687** [comment]
Go to line no. 645, 668 and 691. I wrap code with If conditions

**Comment by hosuaby** [comment]
I found. For which use-case do you introduce those modifications ? If you wrap those code lines into condition and icon object does not exist, bouncing doesn-t work at all, and this made the use of this pugin pointless

**Comment by tomek-servlets** [comment]
Unfortunately, the problem still exists. There ate no if statements in the master.

**Comment by hosuaby** [comment]
@tomek-servlets 
Can you please, present the minimal snippet that reproduce the bug. How do you create marker that has no icon ?

**Comment by tomek-servlets** [comment]
In my opinion before line 645
https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing/blob/master/leaflet.smoothmarkerbouncing.js#L645
there should be 
if(icon)
the same in the  line 687

after adding of these statements there are no more errors in the console

**Comment by hosuaby** [comment]
@tomek-servlets is it bug or just console warning ?

**Comment by tomek-servlets** [comment]
If I remove the if before line 645 I get hundreds of errors:
`leaflet.smoothmarkerbouncing.js:645 Uncaught TypeError: Cannot read property 'style' of undefined at makeMoveStep (leaflet.smoothmarkerbouncing.js:645)`

**Comment by hosuaby** [comment]
@tomek-servlets 
Please, check this demo and tell me if you have error:
http://hosuaby.github.io/Leaflet.SmoothMarkerBouncing/

**Comment by ironbone** [comment]
On your page there I can see no errors.

I created a small page with errors. Click on the map and see the console:
[](https://github.com/ironbone/leaflet-test)

**Comment by hosuaby** [comment]
@ironbone Thanks for concrete example!

Your problem is easy to solve. You made a mistake by calling method `bounce()` before add market to the map:

```javascript
    marker = L.marker(latlng, {icon: personIcon})
        .bindPopup(popupText).bounce()  // <- wrong place to call bounce
        .setBouncingOptions({
            bounceSpeed: bounceSpeed,
        }).addTo(map);
```

To fix, just call `bounce()` after `addTo(map)`:

```javascript
    marker = L.marker(latlng, {icon: personIcon})
        .bindPopup(popupText)
        .setBouncingOptions({
            bounceSpeed: bounceSpeed,
        }).addTo(map).bounce();  // <- bounce called in the end
```

**Comment by ironbone** [comment]
Thank you for your answer.
This was not clear after reading the description of the plugin.

**Comment by hosuaby** [comment]
@ironbone I updated readme to outline importance to add market to map before call `bounce()` method.

**Pull request closed without merging**
